settings:
####is the Plugin Enabled
  enabled: true
####should the plugin check: are they allowed to build
  CheckUserBuilding: true
####should the plugin check: are they allowed to craft
  CheckUserCrafting: true
####should the plugin check: are they allowed to wear
  CheckUserWearing: true
####should the plugin check: are they allowed to use any items
  CheckUserUsing: true
####should the plugin check: are they allowed to echant
  CheckUserEnchanting: true
####should the plugin check: are they allowed to Brew
  CheckUserBrewing: true
####should the plugin check: are they allowed to use Potions
  CheckUserUsePotions: true
####Language is: en = English, de = german/Deutsch
  language: en